services:
    _defaults:
        public: false

    security.acl.dbal.connection:
        alias: database_connection
        public: true

    security.acl.dbal.provider:
        class: Symfony\Component\Security\Acl\Dbal\MutableAclProvider
        arguments:
            - '@security.acl.dbal.connection'
            - '@security.acl.permission_granting_strategy'
            - class_table_name: '%security.acl.dbal.class_table_name%'
              entry_table_name: '%security.acl.dbal.entry_table_name%'
              oid_table_name: '%security.acl.dbal.oid_table_name%'
              oid_ancestors_table_name: '%security.acl.dbal.oid_ancestors_table_name%'
              sid_table_name: '%security.acl.dbal.sid_table_name%'
            - '@?security.acl.cache'

    security.acl.dbal.schema:
        class: Symfony\Component\Security\Acl\Dbal\Schema
        public: true
        arguments:
            - class_table_name: '%security.acl.dbal.class_table_name%'
              entry_table_name: '%security.acl.dbal.entry_table_name%'
              oid_table_name: '%security.acl.dbal.oid_table_name%'
              oid_ancestors_table_name: '%security.acl.dbal.oid_ancestors_table_name%'
              sid_table_name: '%security.acl.dbal.sid_table_name%'
            - '@security.acl.dbal.connection'

    security.acl.dbal.schema_listener:
        class: Symfony\Bundle\AclBundle\EventListener\AclSchemaListener
        arguments:
            - '@security.acl.dbal.schema'

    security.acl.provider:
        alias: security.acl.dbal.provider
        public: true

    Symfony\Component\Security\Acl\Model\AclProviderInterface:
        alias: security.acl.provider

    security.acl.cache.doctrine:
        class: Symfony\Component\Security\Acl\Domain\DoctrineAclCache
        arguments:
            - '@security.acl.cache.doctrine.cache_impl'
            - '@security.acl.permission_granting_strategy'

    security.acl.cache.doctrine.cache_impl:
        alias: doctrine.orm.default_result_cache
